### ISSUE TITLE
New version with latest 'US or SS' fix?

### ISSUE THREAD

**Issue by chris-redekop** [grmble/node-dicom#10]
May I ask for a new patch version with the 'US or SS' fix?  It would be convenient if I didn't have to apply the patch myself after installing v0.4.0.

**Comment by grmble** [comment]
It is published to npmjs as 0.4.1

npm should be able to install from arbitray git https urls as well, so you could have simply done this:

npm install git+https://github.com/grmble/node-dicom.git

Sorry for the delay
