### ISSUE TITLE
do not trust metadata content group length

### ISSUE THREAD

**Issue by csc365kl** [grmble/node-dicom#12]
[1111.zip](https://github.com/grmble/node-dicom/files/377686/1111.zip)
when fs.createReadStream(fileName).pipe(decoder)
happen error 
i dont know why
it can see in dicom tool
think you for you help

**Comment by grmble** [comment]
It is a valid input file, the error you see is a bug. There seems to be a problem with the switch from file meta information to the actual dicom dataset.

Sorry for the delay, I just came back from a vacation. I will have a closer look after I got some sleep

**Comment by grmble** [comment]
Your example file triggered 2 bugs - the siemens-style metadata content group length caused the decoder to switch the transfer syntax too early. And a fixed-length sequence with one empty item produced invalid json output.
