### ISSUE TITLE
tags values with "\"

### ISSUE THREAD

**Issue by KingMario** [grmble/node-dicom#8]
There are "\" in values of tags such as *ImageType*, *ImagePositionPatient*, *ImageOrientationPatient*, *PixelSpacing*, *OverlayOrigin*, etc..

The values retrieved only contains the first part before "\".

**Comment by grmble** [comment]
Yes, and string values should be split at the backslash and an array of strings returned.

An example obtained by parsing an input file and dumping in JSON:

"00080008": {"vr":"CS","Value":["ORIGINAL","PRIMARY",""]},

Which would be the result from an input of ORIGINAL\PRIMARY

**Comment by KingMario** [comment]
I'd like to contribute to node-dicom. How can I get the entire value and split it?
I think I should add a new clss in vrs.js, right?
